// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQhNE76fHpivvr6SNFie5jF6C5SY1KrSs',
    appId: '1:58161293139:web:5b23e0670730f03a50e3a6',
    messagingSenderId: '58161293139',
    projectId: 'leavesystem-520ac',
    authDomain: 'leavesystem-520ac.firebaseapp.com',
    storageBucket: 'leavesystem-520ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSXEt-lE5y5jtYerFh-lgBUgt-vtp-w-8',
    appId: '1:58161293139:android:0b92ea89fb821c4650e3a6',
    messagingSenderId: '58161293139',
    projectId: 'leavesystem-520ac',
    storageBucket: 'leavesystem-520ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQr5iOxdgCfu7gZ9aczJbN6ZnQCVxA0cw',
    appId: '1:58161293139:ios:df598c8adaffc82b50e3a6',
    messagingSenderId: '58161293139',
    projectId: 'leavesystem-520ac',
    storageBucket: 'leavesystem-520ac.firebasestorage.app',
    iosBundleId: 'com.example.leavesystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQr5iOxdgCfu7gZ9aczJbN6ZnQCVxA0cw',
    appId: '1:58161293139:ios:df598c8adaffc82b50e3a6',
    messagingSenderId: '58161293139',
    projectId: 'leavesystem-520ac',
    storageBucket: 'leavesystem-520ac.firebasestorage.app',
    iosBundleId: 'com.example.leavesystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQhNE76fHpivvr6SNFie5jF6C5SY1KrSs',
    appId: '1:58161293139:web:087040798db6575c50e3a6',
    messagingSenderId: '58161293139',
    projectId: 'leavesystem-520ac',
    authDomain: 'leavesystem-520ac.firebaseapp.com',
    storageBucket: 'leavesystem-520ac.firebasestorage.app',
  );
}
